Add basic navbar to homepage
csesoc/cms.csesoc.unsw.edu.au pull request #117
Opened 2022-04-22 11:19 UTC by james-teng-0

- created a very basic navbar
- haven't implemented responsiveness yet - but i've added media queries for the hamburger icon.

![image](https://user-images.githubusercontent.com/74297507/164704580-26bbaccd-c9ee-46b3-8322-beee571520c5.png)

2022-04-25 07:00 UTC, fafnirZ requested changes
please export the hamburger icon as an svg instead of a png, that way we can use code to edit the icon instead of requiring to import another different coloured svg

2022-06-10 09:18 UTC, kylee-software commented
### Changes:

- Added SVGs for hamburger menu icon and  close-menu icon
- Made hamburger menu responsive 

**Navbar for Desktop:**
![desktop view](https://user-images.githubusercontent.com/47190841/173033199-234f4d26-8efc-4162-92ca-373660cdfe51.PNG)


**Hamburger Menu Icon:**
![menu_close](https://user-images.githubusercontent.com/47190841/173033461-00b6a6a2-5762-4cee-ab59-451c6b5fcb71.PNG)


**Hamburger Menu for Tablet:**
![tablet_menu](https://user-images.githubusercontent.com/47190841/173033697-247d069f-7724-443d-a410-f9feade1dc13.PNG)


**Hamburger Menu for Mobile:**
![mobile_menu](https://user-images.githubusercontent.com/47190841/173033817-478eef19-3248-4e16-81ac-249c61733964.PNG)

2022-06-20 05:17 UTC, fafnirZ approved these changes
lgtm, couple of minor changes

2022-06-20 05:17 UTC, fafnirZ commented on Next/src/components/navbar/HamburgerMenu-styled.tsx
> +
add comment somewhere to document the specific breakpoint sizes

2022-06-20 05:17 UTC, fafnirZ commented on Next/src/components/navbar/Navbar.tsx
> +} from "./Navbar-styled";
strange import, when breaking imports into multi lines, usually only 1 per line

2022-08-11 13:50 UTC, fafnirZ commented
@james-teng-0 can you take over, fix the 3 line changes and merge pls

2022-09-01 08:33 UTC, merged