[CMS 259] Added footer, Support and Contact page
csesoc/cms.csesoc.unsw.edu.au pull request #144
Opened 2022-06-03 16:28 UTC by leannachan

2022-06-04 05:54 UTC, fafnirZ commented
@leannachan please check out the assets, there are alot of assets which should be removed, the icons which are flattened should be removed, and imports should not just be named `component-n.svg`

Not exactly sure why Rectangle27-31 is required, you can create rectangles by code instead of having to import it using svg.

2022-06-04 06:00 UTC, fafnirZ commented on Next/src/pages/support.tsx
> +`;
Footer should generally be an external component placed in the `cse-ui-kit` folder

2022-06-07 15:46 UTC, leannachan commented
Preview Contact page:
![image](https://user-images.githubusercontent.com/79742572/172423928-cb943c48-219c-4f76-b1eb-ee7a3d73aace.png)

Preview Support page:
*the footer background is temporary blue to make texts and logo visible as the current homepage background is white
![image](https://user-images.githubusercontent.com/79742572/172423988-6b92a3a4-7c41-4aee-9071-2198fcaf570b.png)

2022-07-07 15:06 UTC, fafnirZ requested changes
a couple of changes

2022-07-07 15:06 UTC, fafnirZ commented on Frontend/src/cse-ui-kit/footer/footer-Styled.tsx
> +    left: 10%;
might need more padding for footer, since it doesnt seem padded enough on the top according to the screenshot

2022-07-07 15:06 UTC, fafnirZ commented on Frontend/src/cse-ui-kit/footer/footer.tsx
> +        <StyledFooter className={className}>
className? I dont think we use this convention for styling our css since we are using styled components

2022-09-21 10:33 UTC, closed without merging