added container component
csesoc/cms.csesoc.unsw.edu.au pull request #68
Opened 2022-03-21 07:22 UTC by leannachan

What I did:
added a container folder under cse-ui-kit.
created files: container-Styled.tsx, container.stories.tsx, container.tsx, index.ts.
created component Container look like below:
![image](https://user-images.githubusercontent.com/79742572/159218864-c8e1a3b0-16ab-4660-9a30-d79e4fcef937.png)

2022-03-21 13:21 UTC, james-teng-0 commented
The container looks good to me but I think you can remove the controls/button related stuff in the container.stories.tsx file so storyboard doesn't render it, since it doesn't do anything for the container.

![image](https://user-images.githubusercontent.com/74297507/159269396-d812c984-58a4-4705-b751-da236b093f2c.png)

2022-03-21 13:23 UTC, james-teng-0 submitted a review, later dismissed
The container looks good to me but I think you can remove the controls/button related stuff in the container.stories.tsx file so storyboard doesn't render it, since it doesn't do anything for the container.

![image](https://user-images.githubusercontent.com/74297507/159269396-d812c984-58a4-4705-b751-da236b093f2c.png)

2022-03-25 14:00 UTC, fafnirZ commented on Frontend/src/cse-ui-kit/container/container.tsx
> +}
@leannachan Container should take in a Children props, and should be 
```js
<StyledContainer>
  {children}
</StyledContainer>
```
this is so we can actually pass children into the container.

2022-03-25 14:03 UTC, fafnirZ requested changes
Overall good progress !!! Please address the changes and re-request review :)

2022-03-25 18:19 UTC, leannachan commented on Frontend/src/cse-ui-kit/container/container.tsx
> +export default function Container({ className}: Props) {
Some changes after the reviews:
- removed the background colour for dotted container
- renamed the container to DottedContainer for all the functions, files and folders
- dotted container take in children props and removed div and header tags

2022-03-26 01:41 UTC, fafnirZ commented
LGTM!!! Great work!! :), 1 more small change though, get rid of all the comments in storybook that links you to a guide, and after you're done with that feel free to merge it into main

2022-03-26 01:41 UTC, fafnirZ approved these changes

2022-03-26 16:45 UTC, merged